version: '3.0'
services:
  mysql:
    image: mysql:5.7
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=PHOENIX_EXMAPLE
      - MYSQL_USER=phoenix
      - MYSQL_PASSWORD=phoenix
      - MYSQL_DATABASE=shopping
    command: [
      '--explicit_defaults_for_timestamp',
      '--character-set-server=utf8',
      '--collation-server=utf8_general_ci'
    ]
    ports:
      - 3306:3306
  zookeeper:
    image: wurstmeister/zookeeper
    volumes:
      - zookeeper_data:/data
    ports:
      - 2182:2182
  kafka:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://127.0.0.1:9092
      KAFKA_CREATE_TOPICS: "shopping"  
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    volumes:
      - kafka_data:/kafka
    depends_on:
      - zookeeper

volumes:
  mysql_data:
  zookeeper_data:
  kafka_data:
